# ==========================================
# 网站基础设置
# ==========================================
title: "Kingsum Chow"              # 网站左上角名称
email: "ksumchow@outlook.com"
description: "Researcher, Lab Director, & Enterprise CEO"
baseurl: ""
url: "https://ye334-git.github.io"

# ==========================================
# 主题与构建
# ==========================================
theme: minima
plugins:
  - jekyll-seo-tag

# 确保解析器设置正确
markdown: kramdown
kramdown:
  input: GFM
